apiVersion: v1
kind: Service
metadata:
  name: app-ui-service-2
spec:
  type: NodePort
  selector:
    app: app-ui-2
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
    nodePort: 30201
