apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-ui
  template:
    metadata:
      labels:
        app: app-ui
    spec:
      containers:
        - name: app-ui
          image: $IMAGE_VERSION
          ports:
            - containerPort: 4000
